name: DBManager
version: '${version}'

main: io.github.earth1283.dBManager.DBManager
paperPluginLoader: io.github.Earth1283.dBManager.DBManagerLoader
api-version: '1.20'
load: STARTUP

authors: [ Earth1283 ]

commands:
  dbmanager:
    description: Manage databases
    aliases: [db]
    permission: dbmanager.admin
